x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 5s
    timeout: 5s
    retries: 5

services:
  gateway:
    <<: *baseService
    image: nginx
    container_name: gateway
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./gateway/:/etc/nginx/templates
    # depends_on:
    #   - graphql-api
    #   - web-app
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/
      SERVICE_PORT: ${SERVICE_PORT}
  
  postgres-db:
    <<: *baseService
    image: postgres
    container_name: sql-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
    volumes:
      - ./persist/sql-db:/var/lib/postgresql/data
    environment:
      PGPORT: ${SERVICE_PORT}
      POSTGRES_HOST: ${DB_CATCHALL}
      POSTGRES_USER: ${DB_CATCHALL}
      POSTGRES_DB: ${DB_CATCHALL}
      POSTGRES_PASSWORD: ${DB_CATCHALL}

  adminer:
    <<: *baseService
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      ADMINER_PORT: ${SERVICE_PORT}